from __future__ import annotations

from pathlib import Path

import yaml

from slam_fusion.datasets.manifests import DatasetManifest, load_manifest
from slam_fusion.evaluation.baselines import (
    BaselineStatus,
    baseline_status_table,
    list_baselines,
)


def test_baseline_registry_separates_claim_maturity() -> None:
    baselines = list_baselines()
    assert baselines
    assert any(spec.status == BaselineStatus.IMPLEMENTED for spec in baselines)
    assert any(spec.status in {BaselineStatus.PROTOTYPE, BaselineStatus.PLANNED} for spec in baselines)
    assert all("state-of-the-art" not in spec.purpose.lower() for spec in baselines)


def test_baseline_status_table_is_documentation_ready() -> None:
    table = baseline_status_table()
    assert table
    required = {"name", "status", "modalities", "purpose", "limitations"}
    assert required.issubset(table[0])


def test_dataset_manifest_validation_reports_missing_root(tmp_path: Path) -> None:
    manifest = DatasetManifest(
        name="EuRoC MAV",
        sequence="MH_01_easy",
        root=tmp_path / "missing",
        modalities=("camera", "imu"),
        citation="Use the official EuRoC MAV citation.",
        license_note="Do not redistribute dataset files.",
    )
    errors = manifest.validate()
    assert any("does not exist" in error for error in errors)


def test_load_manifest_round_trip(tmp_path: Path) -> None:
    root = tmp_path / "sequence"
    root.mkdir()
    path = tmp_path / "manifest.yaml"
    path.write_text(
        yaml.safe_dump(
            {
                "name": "Synthetic",
                "sequence": "nominal",
                "root": str(root),
                "modalities": ["camera", "imu"],
                "citation": "Synthetic data generated by repository code.",
                "license_note": "No external dataset redistributed.",
                "status": "Prototype",
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )

    manifest = load_manifest(path)
    assert manifest.name == "Synthetic"
    assert manifest.sequence == "nominal"
    assert manifest.modalities == ("camera", "imu")
    assert manifest.validate() == []
